# Hardware configuration
# This file is usually generated by running:
# sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
# 
# For now, this is a placeholder. Replace with your actual hardware configuration.

{ config, pkgs, ... }:

{
  # Add your hardware-specific configuration here
  # Examples:
  # boot.initrd.availableKernelModules = [ ... ];
  # hardware.cpu.intel.updateMicrocode = true;
  # etc.
}
